logging:
  level:
    root: DEBUG
    chauffeur.llm: DEBUG
online_radio_box:
  host: https://onlineradiobox.com
spring:
  jackson:
    property-naming-strategy: SNAKE_CASE
radio:
  excluded_artists: SWEEPER, foo
  excluded_titles: spot, foo
gemini:
  host: https://generativelanguage.googleapis.com
  model: gemini-2.0-flash
  api_key: YOUR_GEMINI_API_KEY